### ISSUE TITLE
play deprecations

### ISSUE THREAD

**Issue by pawelpanasewicz** [hmrc/http-verbs#60]
`WSRequest.scala:44` (and possible other code) relies on deprecations in play. 

As a result it's not possible to run parts of the code without running Play Appliacion. Isolation and Encapsulation is broken.

Example. Below code throws **Exception in thread "main" java.lang.RuntimeException: There is no started application**

    object Demo extends App {
      val ws = new uk.gov.hmrc.play.http.ws.WSHttp {
        override val hooks: Seq[HttpHook] = Nil
      }
      implicit val hc = HeaderCarrier()
    
      ws.GET[HttpResponse]("https://google.com") //BOOM
    }

```
Exception in thread "main" java.lang.RuntimeException: There is no started application
	at scala.sys.package$.error(package.scala:27)
	at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
	at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
	at scala.Option.getOrElse(Option.scala:121)
	at play.api.Play$.current(Play.scala:86)
	at uk.gov.hmrc.play.http.ws.WSRequest$class.buildRequest(WSRequest.scala:44)
...
```

**Comment by pawelpanasewicz** [comment]
https://www.playframework.com/documentation/2.5.x/ScalaWS#Directly-creating-WSClient
